prompts: ["A photo of a worker"]
negative_prompt: "bad anatomy,watermark,extra digit,signature,worst quality,jpeg artifacts,normal quality,low quality,long neck,lowres,error,blurry,missing fingers,fewer digits,missing arms,text,cropped,Humpbacked,bad hands,username"
unconditional_prompt: ""
width: 512
height: 512
num_inference_steps: 30
guidance_scale: 7.5
seed: 0
generate_num: 8
save_path: "generated_images_race/{}/{}.png"
# four categories: WMELH, Asian, Black, Indian (uniform)
pmf: [0.25, 0.25, 0.25, 0.25]
alpha: 1.0
